### ISSUE TITLE
RuntineError when training

### ISSUE THREAD

**Issue by cytgh0hu** [justinjohn0306/so-vits-svc-4.0-v2#16]
(sovits4.0) D:\3-Workspace\JupyterLab_Workspace\Sovits\sovits4.2-test\so-vits-svc-4.0-v2>python train.py -c configs/config.json -m 44k
use_cuda,  True
use_cuda,  True
INFO:44k:{'log_interval': 50, 'eval_interval': 1000, 'seed': 1234, 'port': 8001, 'epochs': 10000, 'learning_rate': 0.00015, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 8, 'accumulation_steps':
 1, 'fp16_run': False, 'lr_decay': 0.998, 'segment_size': 10240, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'keep_ckpts': 4}
INFO:44k:{'data_dir': 'dataset', 'dataset_type': 'SingDataset', 'collate_type': 'SingCollate', 'training_filelist': 'filelists/train.txt', 'validation_filelist': 'filelists/val.txt', 'max_wav_value'
: 32768.0, 'sampling_rate': 44100, 'n_fft': 2048, 'fmin': 0, 'fmax': 22050, 'hop_length': 512, 'win_size': 2048, 'acoustic_dim': 80, 'c_dim': 256, 'min_level_db': -115, 'ref_level_db': 20, 'min_db':
 -115, 'max_abs_value': 4.0, 'n_speakers': 200}
INFO:44k:{'hidden_channels': 192, 'spk_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 4, 'kernel_size': 3, 'p_dropout': 0.1, 'prior_hidden_channels': 192, 'prior_filter_channels':
 768, 'prior_n_heads': 2, 'prior_n_layers': 4, 'prior_kernel_size': 3, 'prior_p_dropout': 0.1, 'resblock': '1', 'use_spectral_norm': False, 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_si
zes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 4, 2], 'upsample_initial_channel': 256, 'upsample_kernel_sizes': [16, 16, 8, 4], 'n_harmonic': 64, 'n_bands': 65}
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:426] [c10d] The server socket has failed to bind to [WIN-3OCT327F068]:8001 (system error: 10
048 - 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。).
[W C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:426] [c10d] The server socket has failed to bind to WIN-3OCT327F068:8001 (system error: 1001
3 - 以一种访问权限不允许的方式做了一个访问套接字的尝试。).
[E C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\socket.cpp:462] [c10d] The server socket has failed to listen on any local network address.
Traceback (most recent call last):
  File "D:\3-Workspace\JupyterLab_Workspace\Sovits\sovits4.2-test\so-vits-svc-4.0-v2\train.py", line 436, in <module>
    main()
  File "D:\3-Workspace\JupyterLab_Workspace\Sovits\sovits4.2-test\so-vits-svc-4.0-v2\train.py", line 57, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "C:\Users\Administrator\anaconda3\envs\sovits4.0\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "C:\Users\Administrator\anaconda3\envs\sovits4.0\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "C:\Users\Administrator\anaconda3\envs\sovits4.0\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\sovits4.0\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "D:\3-Workspace\JupyterLab_Workspace\Sovits\sovits4.2-test\so-vits-svc-4.0-v2\train.py", line 74, in run
    dist.init_process_group(backend=  'gloo' if os.name == 'nt' else 'nccl', init_method='env://', world_size=n_gpus, rank=rank)
  File "C:\Users\Administrator\anaconda3\envs\sovits4.0\lib\site-packages\torch\distributed\distributed_c10d.py", line 754, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "C:\Users\Administrator\anaconda3\envs\sovits4.0\lib\site-packages\torch\distributed\rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "C:\Users\Administrator\anaconda3\envs\sovits4.0\lib\site-packages\torch\distributed\rendezvous.py", line 177, in _create_c10d_store
    return TCPStore(
RuntimeError

**Comment by cytgh0hu** [comment]
problem solved by chaging port
